name: shadcn2fluid/about-us
typeName: shadcn2fluid_aboutus
title: About Us
description: Company introduction section with image and story text
group: team
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: Heading
  - identifier: eyebrow
    type: Textarea
    rows: 1
    label: Eyebrow
  - identifier: description
    type: Textarea
    label: Description
    rows: 5
  - identifier: image
    type: File
    label: Image
    allowed: common-image-types
    maxitems: 1
  - identifier: cta_text
    type: Textarea
    rows: 1
    label: Button Text
  - identifier: cta_link
    type: Link
    label: Button Link
