name: shadcn2fluid/copyright-bar
typeName: shadcn2fluid_copyrightbar
title: Copyright Bar
description: Slim copyright bar for the very bottom of the page
group: footer
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:heading'
  - identifier: copyright
    type: Textarea
    rows: 1
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:copyright_text'
    required: true
  - identifier: link_items
    type: Collection
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:links'
    fields:
      - identifier: label
        type: Textarea
        rows: 1
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:label_field'
        required: true
      - identifier: link
        type: Link
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:link'
  - identifier: alignment
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:alignment'
    items:
      - label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:item.left'
        value: left
      - label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:item.center'
        value: center
      - label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:item.between'
        value: between
    default: between
