name: shadcn2fluid/search-header
typeName: shadcn2fluid_searchheader
title: Search Header
description: Header block with headline, supporting text, and search form
group: navigation
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: Heading

  - identifier: eyebrow
    type: Textarea
    rows: 1
    label: Eyebrow

  - identifier: subheadline
    type: Textarea
    label: Subheadline
    rows: 2

  - identifier: form_action
    type: Link
    label: Form Action

  - identifier: placeholder
    type: Textarea
    rows: 1
    label: Placeholder

  - identifier: button_text
    type: Textarea
    rows: 1
    label: Button Text
