name: shadcn2fluid/header-banner
typeName: shadcn2fluid_headerbanner
title: Banner Header
description: Full-width banner header with background color and optional image
group: navigation
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:heading'
  - identifier: subheadline
    type: Textarea
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:description'
    rows: 3
  - identifier: background_image
    type: File
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:background_image'
    allowed: common-image-types
    maxitems: 1
  - identifier: variant
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:style'
    items:
      - label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:item.default'
        value: default
      - label: Dark
        value: dark
      - label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:item.primary'
        value: primary
    default: default
  - identifier: button_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:button_text'
  - identifier: button_link
    type: Link
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:button_link'
