name: shadcn2fluid/newsletter-inline
typeName: shadcn2fluid_newsletterinline
title: Newsletter Inline
description: Compact inline newsletter signup form
group: conversion
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:heading'
  - identifier: description_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:description'
  - identifier: form_action
    type: Link
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:form_action'
  - identifier: placeholder
    type: Textarea
    rows: 1
    label: Placeholder
  - identifier: button_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:button_text'
