name: shadcn2fluid/company-history
typeName: shadcn2fluid_companyhistory
title: Company History
description: Timeline of company milestones and historical events
group: team
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:heading'
  - identifier: subheadline
    type: Textarea
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:subheadline'
    rows: 2
  - identifier: events
    type: Collection
    label: Events
    minItems: 1
    fields:
      - identifier: year
        type: Textarea
        rows: 1
        label: Year
        required: true
      - identifier: title
        type: Textarea
        rows: 1
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:title'
        required: true
      - identifier: description
        type: Textarea
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:description'
        rows: 2
