name: shadcn2fluid/content-grid
typeName: shadcn2fluid_contentgrid
title: Content Grid
description: Flexible grid of rich text content cards
group: content
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:heading'
  - identifier: columns
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:columns'
    items:
      - label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:item.2_columns'
        value: '2'
      - label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:item.3_columns'
        value: '3'
    default: '2'
  - identifier: items
    type: Collection
    label: Grid Items
    minItems: 2
    fields:
      - identifier: title
        type: Textarea
        rows: 1
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:title'
      - identifier: content
        type: Textarea
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:content'
        enableRichtext: true
        rows: 4
      - identifier: link
        type: Link
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:link'
