name: shadcn2fluid/directions
typeName: shadcn2fluid_directions
title: Directions
description: How to reach us with multiple transport options
group: conversion
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: Heading
  - identifier: subheadline
    type: Textarea
    label: Subheadline
    rows: 2
  - identifier: routes
    type: Collection
    label: Routes
    minItems: 1
    fields:
      - identifier: mode
        type: Textarea
        rows: 1
        label: Transport Mode
        required: true
      - identifier: description
        type: Textarea
        label: Directions
        rows: 3
