name: shadcn2fluid/team-cta
typeName: shadcn2fluid_teamcta
title: Team CTA
description: Call to action for joining the team with open positions count
group: team
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:heading'
  - identifier: description
    type: Textarea
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:description'
    rows: 3
  - identifier: open_count
    type: Textarea
    rows: 1
    label: Open Positions Count
  - identifier: cta_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:button_text'
  - identifier: cta_link
    type: Link
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:button_link'
  - identifier: image
    type: File
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:background_image'
    allowed: common-image-types
    maxitems: 1
