name: shadcn2fluid/alert
title: ShadCN Alert / Callout
description: Alert boxes for important messages, tips, warnings
group: common
prefixFields: false
fields:
  - identifier: variant
    type: Select
    renderType: selectSingle
    label: Alert Type
    fieldWizard:
      selectIcons:
        disabled: false
    items:
      - label: Default
        value: default
        icon: shadcn2fluid-alert-default
      - label: Info
        value: info
        icon: shadcn2fluid-alert-info
      - label: Success
        value: success
        icon: shadcn2fluid-alert-success
      - label: Warning
        value: warning
        icon: shadcn2fluid-alert-warning
      - label: Destructive / Error
        value: destructive
        icon: shadcn2fluid-alert-destructive
    default: default

  - identifier: title
    type: Text
    label: Alert Title

  - identifier: content
    type: Textarea
    label: Alert Content
    enableRichtext: true
    rows: 3
    required: true

  - identifier: show_icon
    type: Checkbox
    label: Show Icon
    default: 1

  - identifier: dismissible
    type: Checkbox
    label: Dismissible
    description: Allow users to close the alert
    default: 0
