name: shadcn2fluid/feedback-form
typeName: shadcn2fluid_feedbackform
title: Feedback Form
description: User feedback collection form with rating option
group: conversion
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:heading'
  - identifier: description
    type: Textarea
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:description'
    rows: 2
  - identifier: form_action
    type: Link
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:form_action'
  - identifier: submit_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:submit_text'
    default: Send feedback
  - identifier: show_rating
    type: Checkbox
    label: Show Rating Field
    default: 1
