name: shadcn2fluid/hero-form
typeName: shadcn2fluid_heroform
title: Hero Form
description: Hero section with inline signup or contact form
group: hero
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: Heading
  - identifier: subheadline
    type: Textarea
    label: Subheadline
    rows: 3
  - identifier: form_action
    type: Link
    label: Form Action URL
  - identifier: input_placeholder
    type: Textarea
    rows: 1
    label: Input Placeholder
  - identifier: button_text
    type: Textarea
    rows: 1
    label: Button Text
  - identifier: privacy_notice
    type: Textarea
    rows: 1
    label: Privacy Text
  - identifier: badge_text
    type: Textarea
    rows: 1
    label: Badge Text
