name: shadcn2fluid/hero-carousel
typeName: shadcn2fluid_herocarousel
title: Hero Carousel
description: Hero with rotating slides of headline, text, and image
group: hero
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:heading'
  - identifier: subheadline
    type: Textarea
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:subheadline'
    rows: 3
  - identifier: slides
    type: Collection
    label: Slides
    minItems: 1
    fields:
      - identifier: title
        type: Textarea
        rows: 1
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:title'
      - identifier: description
        type: Textarea
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:description'
        rows: 2
      - identifier: image
        type: File
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:image'
        allowed: common-image-types
        maxitems: 1
      - identifier: button_text
        type: Textarea
        rows: 1
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:button_text'
      - identifier: button_link
        type: Link
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:button_link'
