name: shadcn2fluid/blog-teasers
typeName: shadcn2fluid_blogteasers
title: Blog Teasers
description: Article teaser cards for news, blog, or resource sections
group: content
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:heading'

  - identifier: subheadline
    type: Textarea
    label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:subheadline'
    rows: 2

  - identifier: columns
    type: Select
    renderType: selectSingle
    label: Teaser Columns
    items:
      - label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:item.2_columns'
        value: '2'
      - label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:item.3_columns'
        value: '3'
    default: '3'

  - identifier: posts
    type: Collection
    label: Posts
    minItems: 1
    fields:
      - identifier: image
        type: File
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:image'
        allowed: common-image-types
        maxitems: 1

      - identifier: category
        type: Textarea
        rows: 1
        label: Category

      - identifier: meta
        type: Textarea
        rows: 1
        label: Meta
        description: e.g. 5 min read or Mar 18, 2026

      - identifier: title
        type: Textarea
        rows: 1
        label: 'LLL:EXT:shadcn2fluid_templates/Resources/Private/Language/labels.xlf:title'
        required: true

      - identifier: excerpt
        type: Textarea
        label: Excerpt
        rows: 3

      - identifier: link
        type: Link
        label: Post Link
